name: Publish
on:
  push:
    branches:
      - master
jobs:

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - uses: borales/actions-yarn@v2.0.0
        with:
        cmd: install

#      - name: Build and run test
#        env:
#          DATABASE_URL: postgres://postgres:@localhost:5432/test
#          REDIS_URL: redis://localhost:6379/0
#          RAILS_ENV: test
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: postgres
#        run: |
#          sudo apt-get -yqq install libpq-dev
#          gem install bundler
#          bundle install --jobs 4 --retry 3
#          bundle exec rake db:create
#          bundle exec rake db:migrate
#          #undle exec rspec .

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: rails-app
          environment_name: Railsapp-env
          version_label: 1
          region: us-west-2
          deployment_package: deploy.zip
